import { DM_Sans } from "next/font/google";
import "./globals.css";
import { CustomProvider } from "rsuite";
import 'rsuite/dist/rsuite-no-reset.min.css';

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "NepGov",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const theme = {
    primary: "#3560AD",
  };
  return (
    <html lang="en">
      <CustomProvider>
        <body className={`${dmSans.variable} bg-white text-black`}>
          {children}
        </body>
      </CustomProvider>
    </html>
  );
}
