import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "@/components/common/Providers";
import { usePathname } from "next/navigation";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "NepGov",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.svg'
  },
};

export default function RootLayout({ children }) {
  const handleTranslate = (language) => {
    // Get current path including query parameters
    const currentPath = usePathname();
    const fullUrl = `https://nepgov-frontend.vercel.app${currentPath}`;
    const translateUrl = `https://translate.google.com/translate?sl=auto&tl=${language}&u=${encodeURIComponent(fullUrl)}`;
    window.open(translateUrl, '_blank');
  };
  return (
    <html lang="en">
      <body className={`${dmSans.variable} bg-white text-black`}>
        <button onClick={handleTranslate}>Change Lang</button>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
